imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
    secret: "secretkey"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ["twig"]